package com.lei.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lei.voice_tuling.model.ChatRecords;

import com.lei.greendao.ChatRecordsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatRecordsDaoConfig;

    private final ChatRecordsDao chatRecordsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatRecordsDaoConfig = daoConfigMap.get(ChatRecordsDao.class).clone();
        chatRecordsDaoConfig.initIdentityScope(type);

        chatRecordsDao = new ChatRecordsDao(chatRecordsDaoConfig, this);

        registerDao(ChatRecords.class, chatRecordsDao);
    }
    
    public void clear() {
        chatRecordsDaoConfig.clearIdentityScope();
    }

    public ChatRecordsDao getChatRecordsDao() {
        return chatRecordsDao;
    }

}
